### ISSUE TITLE
Create Issues for Milestones

### ISSUE THREAD

**Issue by actual-saurabh** [BaapWP/Micros#1]
- [ ] For https://github.com/BaapWP/Micros/milestone/2
- [ ] For https://github.com/BaapWP/Micros/milestone/1
- [ ] For https://github.com/BaapWP/Micros/milestone/3
